services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=aka.123#
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db2:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=myuser2
      - POSTGRES_PASSWORD=mypassword2
      - POSTGRES_DB=mydatabase2
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser2 -d mydatabase2"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data2: